# Generated by Django 6.0 on 2025-12-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_category_ticket_resolved_at_ticket_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
